name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write   # allow pushing to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Scala and SBT
        uses: olafurpg/setup-scala@v14
        with:
          java-version: adopt@1.11

      - name: Build project
        run: sbt fullOptCompileCopy

      - name: Prepare files for GitHub Pages
        run: |
          mkdir -p ./publish-folder/public/js
          cp ./index.html ./publish-folder/
          cp -r ./public/* ./publish-folder/public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish-folder
